/**
 * OOPSBannerApp UC2 – Banner Display Application
 * * This class demonstrates the creation of a visual banner displaying the word "OOPS"
 * using ASCII art composed of asterisks (*) and spaces. The banner is printed to the
 * console using individual print statements for each line, creating a decorative
 * text effect.
 * * <p>The banner is generated by printing predefined string patterns line by line,
 * where each line contributes to forming the letters O, O, P, and S in a stylized format.
 * This extends a basic user story by adding visual presentation to a simple message output.
 * </p>
 * * @author Developer
 * @version 2
 */

// Extend the User Story 1 to display the message "OOPS" in a banner format
// using characters formed by spaces and asterisks (*) to create a visual
// effect for each letter in the message. Use print statements for each line
// instead of a loop.

public class OOPSBannerApp {

    // Main method to run the banner display
    // Print each line of the OOPS banner to create the visual effect for the
    // message "OOPS". Construct each line using string concatenation.
    // Each line corresponds to a row in the banner for the letters O, O, P, S.
    // Using individual print statements for each line.
    Run | Debug
    public static void main(String[] args) {
	// Hint:
// 1. Define a String array with a size equal to the number of lines in the banner
// 2. Populate each index of the array with the corresponding banner line using String.join()
// 3. Use a for-each loop to iterate through the array and print each line
// Example of OS banner line creation: Firstly populate the array as below

lines[0] = String.join(" ", "  *** ", " ***** ");
lines[1] = String.join(" ", " ** ** ", " ** ");
lines[2] = String.join(" ", "** **", "** ");
lines[3] = String.join(" ", "** **", " ***** ");
lines[4] = String.join(" ", "** **", "     **");
lines[5] = String.join(" ", " ** ** ", " ** **");
lines[6] = String.join(" ", "  *** ", " ***** ");

// Then use a for-each loop to print each line
for (String line : lines) {
    System.out.println(line);
}

    }
}